parameters:
    kcmus_cache.data_collector.class: KCMUS\Bundle\CacheBundle\DataCollector\CacheDataCollector
    kcmus_cache.data_collector.template: KCMUSCacheBundle:Collector:cache.html.twig

services:
   data_collector.cache:
        class: %kcmus_cache.data_collector.class%
        tags:
            - { name: data_collector, template: %kcmus_cache.data_collector.template%, id: 'cache' }

