parameters:
    kcmus_cache.abstract.apc.class: Doctrine\Common\Cache\ApcCache
    kcmus_cache.abstract.array.class: Doctrine\Common\Cache\ArrayCache
    kcmus_cache.abstract.file_system.class: Doctrine\Common\Cache\FilesystemCache
    kcmus_cache.abstract.memcache.class: Doctrine\Common\Cache\MemcacheCache
    kcmus_cache.abstract.memcached.class: Doctrine\Common\Cache\MemcachedCache
    kcmus_cache.abstract.redis.class: Doctrine\Common\Cache\RedisCache
    kcmus_cache.abstract.php_file.class: Doctrine\Common\Cache\PhpFileCache
    kcmus_cache.abstract.win_cache.class: Doctrine\Common\Cache\WinCacheCache
    kcmus_cache.abstract.xcache.class: Doctrine\Common\Cache\XcacheCache
    kcmus_cache.abstract.zend_data.class: Doctrine\Common\Cache\ZendDataCache
    kcmus_cache.session.handler.class: KCMUS\Bundle\CacheBundle\Session\SessionHandler
    kcmus_cache.service.class: KCMUS\Bundle\CacheBundle\Service\CacheService

services:
    kcmus_cache.abstract.apc:
        class: %kcmus_cache.abstract.apc.class%
        abstract: true

    kcmus_cache.abstract.array:
        class: %kcmus_cache.abstract.array.class%
        abstract: true

    kcmus_cache.abstract.file_system:
        class: %kcmus_cache.abstract.file_system.class%
        abstract: true

    kcmus_cache.abstract.memcache:
        class: %kcmus_cache.abstract.memcache.class%
        abstract: true

    kcmus_cache.abstract.memcached:
        class: %kcmus_cache.abstract.memcached.class%
        abstract: true

    kcmus_cache.abstract.redis:
        class: %kcmus_cache.abstract.redis.class%
        abstract: true

    kcmus_cache.abstract.php_file:
        class: %kcmus_cache.abstract.php_file.class%
        abstract: true

    kcmus_cache.abstract.win_cache:
        class: %kcmus_cache.abstract.win_cache.class%
        abstract: true

    kcmus_cache.abstract.xcache:
        class: %kcmus_cache.abstract.xcache.class%
        abstract: true

    kcmus_cache.zend_data:
        class: %kcmus_cache.abstract.zend_data.class%
        abstract: true
